function [L1,L2,L3] = calcLinksVertex(in1,in2,in3,half_link_width)
%CALCLINKSVERTEX
%    [L1,L2,L3] = CALCLINKSVERTEX(IN1,IN2,IN3,HALF_LINK_WIDTH)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    31-Dec-2015 13:18:34

l1 = in2(:,1);
l2 = in2(:,2);
l3 = in2(:,3);
psi0 = in1(:,3);
q1 = in3(:,1);
q2 = in3(:,2);
q3 = in3(:,3);
x0 = in1(:,1);
y0 = in1(:,2);
t2 = cos(psi0);
t3 = cos(q1);
t4 = sin(psi0);
t5 = sin(q1);
t6 = t2.*t3;
t12 = t4.*t5;
t7 = t6-t12;
t8 = t2.*t5;
t9 = t3.*t4;
t10 = t8+t9;
t11 = half_link_width+l1;
t13 = t7.*t11;
t14 = half_link_width.*t10;
t15 = half_link_width.*t7;
t16 = t10.*t11;
L1 = reshape([x0-half_link_width.*t7-half_link_width.*t10,-t14+t15+y0,t13+x0-half_link_width.*t10,t15+t16+y0,t13+t14+x0,-t15+t16+y0,t14+x0-half_link_width.*t7,-t14-t15+y0],[2, 4]);
if nargout > 1
    t17 = cos(q2);
    t18 = sin(q2);
    t19 = t7.*t17;
    t26 = t10.*t18;
    t20 = t19-t26;
    t21 = t10.*t17;
    t22 = t7.*t18;
    t23 = t21+t22;
    t24 = l1.*t2.*t3;
    t25 = half_link_width+l2;
    t27 = t20.*t25;
    t28 = half_link_width.*t23;
    t29 = half_link_width.*t20;
    t30 = l1.*t2.*t5;
    t31 = l1.*t3.*t4;
    t32 = t23.*t25;
    L2 = reshape([t24+x0-half_link_width.*t20-half_link_width.*t23-l1.*t4.*t5,-t28+t29+t30+t31+y0,t24+t27+x0-half_link_width.*t23-l1.*t4.*t5,t29+t30+t31+t32+y0,t24+t27+t28+x0-l1.*t4.*t5,-t29+t30+t31+t32+y0,t24+t28+x0-half_link_width.*t20-l1.*t4.*t5,-t28-t29+t30+t31+y0],[2, 4]);
end
if nargout > 2
    t33 = cos(q3);
    t34 = sin(q3);
    t35 = t20.*t33;
    t42 = t23.*t34;
    t36 = t35-t42;
    t37 = t23.*t33;
    t38 = t20.*t34;
    t39 = t37+t38;
    t40 = l2.*t7.*t17;
    t41 = half_link_width+l3;
    t43 = t36.*t41;
    t44 = half_link_width.*t39;
    t45 = half_link_width.*t36;
    t46 = l2.*t10.*t17;
    t47 = l2.*t7.*t18;
    t48 = t39.*t41;
    L3 = reshape([t24+t40+x0-half_link_width.*t36-half_link_width.*t39-l1.*t4.*t5-l2.*t10.*t18,t30+t31-t44+t45+t46+t47+y0,t24+t40+t43+x0-half_link_width.*t39-l1.*t4.*t5-l2.*t10.*t18,t30+t31+t45+t46+t47+t48+y0,t24+t40+t43+t44+x0-l1.*t4.*t5-l2.*t10.*t18,t30+t31-t45+t46+t47+t48+y0,t24+t40+t44+x0-half_link_width.*t36-l1.*t4.*t5-l2.*t10.*t18,t30+t31-t44-t45+t46+t47+y0],[2, 4]);
end
